### PR TITLE
Loginpage

### PR DESCRIPTION
**Pull request by verasunyy**
fixed the usertype issue

### CODE REVIEW

**Review by oliwright1994 — APPROVED** [review]
Looks good, only thing is theres quite a lot of stuff commented out. Are these lines that you're still working on and will be used later?

**Comment by verasunyy** [comment]
yes, I need to test it one more time after merge. I'll clean it up after that.

**Comment by oliwright1994** [comment]
Sounds good!

**Comment by verasunyy** [comment]
Are you on slack right now? Which part are you working on right now?

**Pull request merged**
